Environment:

<Environment>:
    orientation: "horizontal"
    Button:
        text: "A"

    BoxLayout:
        orientation: "vertical"
        Button:
            text: "Week"
        Button:
            text: "Closed tasks"
    
<MainWidget>:
    Label: 
        text: "Hello"
        size: "40dp", "20dp"
        pos: "10dp", "200dp"
    Button: 
        text: "Hello2"
        size: "40dp", "20dp"
        pos: "100dp", "200dp"